- intent: faq/ask_getTemplateApplication
  examples: |
    - Cum fac o cerere?
    - Ai un model de cerere pentru secretariat?
    - Există vreun model de cerere pentru secretariat?
    - Îmi poți arâta un model de cerere?
    - Îmi poți trimite un model de cerere?
    - Mă poți ajuta să fac o cerere?
    - Ajută-mă să găsesc un model de cerere!
    - Am nevoie sa imi arati un model de cerere!
    - Vreau sa imi arati un model de cerere!
    